<a href="https://colab.research.google.com/github/TwoManyHands/Algorithms/blob/main/bank_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
import pandas as pd
import numpy as np
import altair as alt
from sklearn.model_selection import train_test_split

bankData=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Chapter3/bank-full.csv',sep=';')

In [9]:
from pandas import set_option

In [22]:
bankNumeric=bankData[['age','balance','day','duration','campaign','pdays','previous']]

# Standardise data (mean 0, stdev 1)

In [13]:
from sklearn.preprocessing import StandardScaler
from numpy import set_printoptions

In [14]:
set_printoptions(precision=3)
scaling = StandardScaler().fit(bankNumeric)
rescaledNum=scaling.fit_transform(bankNumeric)

In [17]:
rescaledNum[0:5]

array([[ 1.607,  0.256,  0.011, -0.569, -0.411, -0.252],
       [ 0.289, -0.438, -0.416, -0.569, -0.411, -0.252],
       [-0.747, -0.447, -0.707, -0.569, -0.411, -0.252],
       [ 0.571,  0.047, -0.645, -0.569, -0.411, -0.252],
       [-0.747, -0.447, -0.234, -0.569, -0.411, -0.252]])

# Normalise

In [23]:
from sklearn.preprocessing import Normalizer
normaliser=Normalizer().fit(bankNumeric)
normalisedSum=normaliser.transform(bankNumeric)

In [24]:
print(normalisedSum)

[[ 2.686e-02  9.923e-01  2.315e-03 ...  4.630e-04 -4.630e-04  0.000e+00]
 [ 2.750e-01  1.812e-01  3.125e-02 ...  6.249e-03 -6.249e-03  0.000e+00]
 [ 3.974e-01  2.408e-02  6.021e-02 ...  1.204e-02 -1.204e-02  0.000e+00]
 ...
 [ 1.235e-02  9.805e-01  2.917e-03 ...  8.579e-04  3.157e-02  5.147e-04]
 [ 6.775e-02  7.940e-01  2.021e-02 ...  4.754e-03 -1.189e-03  0.000e+00]
 [ 1.234e-02  9.906e-01  5.668e-03 ...  6.669e-04  6.269e-02  3.668e-03]]
